/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.OtpisMonografskihPublikacija;
import domen.Revizija;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;

/**
 *
 * @author Jaca
 */
public class IzmeniOtpisMonoPForma extends javax.swing.JDialog {

    OtpisMonografskihPublikacija otpis;
    
    /**
     * Creates new form IzmeniOtpisMonoPForma
     */
    public IzmeniOtpisMonoPForma(java.awt.Frame parent, boolean modal, OtpisMonografskihPublikacija otpis) {
        super(parent, modal);
        this.otpis = otpis;
        initComponents();
        setLocationRelativeTo(null);
        txtIdIzvestaja.setText(String.valueOf(otpis.getIzvestaj().getIzvestaj().getIdIzvestaja()));
        txtIdRevizije.setText(String.valueOf(otpis.getRevizija().getIdRevizije()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdIzvestaja = new javax.swing.JTextField();
        txtIdRevizije = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("idRevizije:");

        jLabel2.setText("idIzvestaja:");

        txtIdIzvestaja.setText(" ");

        txtIdRevizije.setText(" ");

        btnIzmeni.setText("IZMENI");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdRevizije, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdIzvestaja, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdIzvestaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdRevizije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        
        try{
            
            int idIzvestaja = Integer.parseInt(txtIdIzvestaja.getText());
            
            otpis.getIzvestaj().getIzvestaj().setIdIzvestaja(idIzvestaja);
            
            int idOptisaM = otpis.getIdOtpisaM();
            int manjak = otpis.getManjak();
            int skart = otpis.getSkart();
            int idRevizije = Integer.parseInt(txtIdRevizije.getText());
            
            Revizija revizija = Kontroler.getInstance().vratiKonkretnuReviziju(idRevizije);
            
            OtpisMonografskihPublikacija noviOtpis = new OtpisMonografskihPublikacija(otpis.getIzvestaj(),idOptisaM, manjak, skart, revizija);
            
            if(idRevizije == otpis.getRevizija().getIdRevizije()){
                noviOtpis = new OtpisMonografskihPublikacija(otpis.getIzvestaj(),idOptisaM, manjak, skart, null);

            }
            
            boolean uspesno = Kontroler.getInstance().azurirajOtpisMono(noviOtpis);
            
            if(uspesno){
                JOptionPane.showMessageDialog(this, "Uspesno azuriran otpis mono publikacije!");
                
                this.dispose();
            }
            
             } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(IzmeniOtpisMonoPForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtIdIzvestaja;
    private javax.swing.JTextField txtIdRevizije;
    // End of variables declaration//GEN-END:variables
}
